// <auto-generated />
using System;
using EmployeeManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230901100445_mig4")]
    partial class mig4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 101,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 102,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 103,
                            DepartmentName = "Sales"
                        },
                        new
                        {
                            DepartmentId = 104,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            DepartmentId = 105,
                            DepartmentName = "Payroll"
                        },
                        new
                        {
                            DepartmentId = 106,
                            DepartmentName = "Business"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1981, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 102,
                            Email = "Sam@Prag.com",
                            FirstName = "Sam",
                            Gender = 0,
                            LastName = "Galloway",
                            PhotoPath = "images/sam.jpg"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1990, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 102,
                            Email = "david@ross.com",
                            FirstName = "David",
                            Gender = 0,
                            LastName = "Finch",
                            PhotoPath = "images/david.jpg"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateTime(2000, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 103,
                            Email = "richard@b.com",
                            FirstName = "Richard",
                            Gender = 0,
                            LastName = "Branson",
                            PhotoPath = "images/riche.jpg"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 104,
                            Email = "Folly@mike.com",
                            FirstName = "Folly",
                            Gender = 0,
                            LastName = "Mike",
                            PhotoPath = "images/folly.jpg"
                        },
                        new
                        {
                            EmployeeId = 5,
                            DateOfBirth = new DateTime(1994, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 104,
                            Email = "Lysander@c.com",
                            FirstName = "Lysander",
                            Gender = 0,
                            LastName = "Collins",
                            PhotoPath = "images/lysander.jpg"
                        },
                        new
                        {
                            EmployeeId = 6,
                            DateOfBirth = new DateTime(1997, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 103,
                            Email = "Reginald@a.com",
                            FirstName = "Reginald",
                            Gender = 0,
                            LastName = "Amgoth",
                            PhotoPath = "images/reginald.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
